on:
  workflow_call:
    inputs:
      nuxt-output-path:
        type: string
        default: ".output/public"
        description: Output path of nuxt generate.
      functions-path:
        type: string
        default: functions
        description: Path to the functions to deploy
      nuxt-src-path:
        type: string
        default: "."
        description: Path to the nuxt src
      node-version:
        type: string
        default: 20
        description: Node.js version
      workload-identity-provider:
        type: string
        required: true
        description: ID of the workload identity provider
      service-account:
        type: string
        required: true
        description: Service account to use when deploying
      workload-identity-audience:
        type: string
        required: true
        description: Audience of the workload identity

jobs:
  changed-files:
    name: Get Changed Files
    runs-on: ubuntu-latest
    outputs:
      hosting: ${{ steps.changed-functions-files.outputs.only_changed == 'false' }}
      functions: ${{ steps.changed-functions-files.outputs.any_changed == 'true' }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Changed Files Under Functions
        id: changed-functions-files
        uses: tj-actions/changed-files@v35
        with:
          since_last_remote_commit: true
          files: |
            ${{ inputs.functions-path }}/**

  nuxt-build:
    name: Nuxt Build
    needs:
      - changed-files
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' || needs.changed-files.outputs.hosting == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: yarn
          cache-dependency-path: ${{ inputs.nuxt-src-path }}/yarn.lock

      - name: yarn install
        run: yarn install --frozen-lockfile
        working-directory: ${{ inputs.nuxt-src-path }}

      - name: Build
        run: NODE_OPTIONS="--max_old_space_size=5120" yarn generate
        env: ${{ secrets }}
        working-directory: ${{ inputs.nuxt-src-path }}

      - name: Zip artifact
        run: zip -qq -r ~/artifact.zip "${{ inputs.nuxt-src-path }}/${{ inputs.nuxt-output-path }}"

      - uses: actions/upload-artifact@v3
        with:
          name: nuxt-generated
          path: |
            ~/artifact.zip

  deploy-hosting:
    name: Deploy to Hosting
    needs:
      - changed-files
      - nuxt-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: nuxt-generated

      - name: Unzip artifact
        run: unzip artifact.zip

      - name: Install Firebase CLI
        run: yarn global add firebase-tools

      - name: 'Authenticate to Google Cloud'
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ inputs.workload-identity-provider }}
          service_account: ${{ inputs.service-account }}
          audience: ${{ inputs.workload-identity-audience }}

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting

      - uses: geekyeggo/delete-artifact@v2
        with:
          name: nuxt-generated

  deploy-to-functions:
    name: "Deploy to Functions"
    runs-on: ubuntu-latest
    needs:
      - changed-files
    if: ${{ github.event_name != 'repository_dispatch' && ( github.event_name == 'workflow_dispatch' || needs.changed-files.outputs.functions == 'true' ) }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - name: yarn install
        run: |
          yarn install --frozen-lockfile
          cd functions && yarn install --frozen-lockfile

      - name: Install Firebase CLI
        run: yarn global add firebase-tools

      - name: 'Authenticate to Google Cloud'
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ inputs.workload-identity-provider }}
          service_account: ${{ inputs.service-account }}
          audience: ${{ inputs.workload-identity-audience }}

      - name: Deploy to Cloud Functions
        run: firebase deploy --only functions

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
